CREATE TABLE IF NOT EXISTS saved_job_records (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_number      VARCHAR(50) NOT NULL,
    invoice_date        DATE NOT NULL,
    client_name         VARCHAR(255) NULL,
    event_name          VARCHAR(255) NOT NULL,
    event_date          DATE NULL,
    venue               VARCHAR(255) NULL,
    staff_count         INT UNSIGNED NOT NULL DEFAULT 0,
    hours_per_staff     DECIMAL(6,2) NOT NULL DEFAULT 0,
    hourly_rate         DECIMAL(8,2) NOT NULL DEFAULT 0,
    total_hours         DECIMAL(8,2) NOT NULL DEFAULT 0,
    total_amount        DECIMAL(12,2) NOT NULL DEFAULT 0,
    line_description    VARCHAR(500) NULL,
    notes               TEXT NULL,
    status              ENUM('draft','sent','paid','void') NOT NULL DEFAULT 'draft',
    currency            CHAR(3) NOT NULL DEFAULT 'EUR',
    event_id            INT UNSIGNED NULL,
    created_by          INT UNSIGNED NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_saved_job_invoice_number (invoice_number),
    INDEX idx_saved_job_invoice_date (invoice_date),
    INDEX idx_saved_job_status (status),
    INDEX idx_saved_job_event (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
